name: CI

# Run the workflow on every push to any branch
on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repo code
      - name: Check out code
        uses: actions/checkout@v3
      
      # Step 2: Set up ruby env
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # specify your Ruby version
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      
      # Step 4: Run tests
      - name: Run tests with Rake
        run: |
          bundle exec rake test
